const { PrismaClient } = require('@prisma/client');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, BorderStyle, WidthType, ShadingType } = require('docx');
const fs = require('fs');
const prisma = new PrismaClient();

async function generateFinancialReport(monthStr) {
  // 1. Get Real Data
  const targetDate = monthStr ? new Date(`${monthStr}-01`) : new Date();
  const start = new Date(targetDate.getFullYear(), targetDate.getMonth(), 1);
  const end = new Date(targetDate.getFullYear(), targetDate.getMonth() + 1, 0);

  const txs = await prisma.transaction.findMany({
    where: { date: { gte: start, lte: end }, status: 'COMPLETED' }
  });

  const income = txs.filter(t => t.type === 'INCOME').reduce((s, t) => s + t.amount, 0);
  const expense = txs.filter(t => t.type === 'EXPENSE').reduce((s, t) => s + t.amount, 0);

  // 2. Build DOCX
  const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
  const borders = { top: border, bottom: border, left: border, right: border };
  const cellMargins = { top: 120, bottom: 120, left: 180, right: 180 };

  const doc = new Document({
    styles: {
        default: { document: { run: { font: "Arial", size: 24 } } },
        paragraphStyles: [
            { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
              run: { size: 36, bold: true, color: "1F4E78" },
              paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 } },
        ]
    },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 }, // US Letter
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }
        }
      },
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: "AI.EZDOC FINANCIAL REPORT", bold: true, size: 48 })],
          spacing: { after: 400 }
        }),
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun(`Summary for ${start.toLocaleDateString('th-TH', { month: 'long', year: 'numeric' })}`)]
        }),
        new Table({
          width: { size: 9360, type: WidthType.DXA },
          columnWidths: [4680, 4680], // FIXED: Added column widths for Google Docs compatibility
          rows: [
            new TableRow({
              children: [
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  margins: cellMargins,
                  children: [new Paragraph("Total Income")] 
                }),
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  margins: cellMargins,
                  children: [new Paragraph(`${income.toLocaleString()} THB`)] 
                }),
              ]
            }),
            new TableRow({
              children: [
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  margins: cellMargins,
                  children: [new Paragraph("Total Expense")] 
                }),
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  margins: cellMargins,
                  children: [new Paragraph(`${expense.toLocaleString()} THB`)] 
                }),
              ]
            }),
            new TableRow({
              children: [
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  shading: { fill: "D5E8F0", type: ShadingType.CLEAR }, 
                  margins: cellMargins,
                  children: [new Paragraph({ children: [new TextRun({ text: "Net Profit", bold: true })] })] 
                }),
                new TableCell({ 
                  borders, 
                  width: { size: 4680, type: WidthType.DXA }, 
                  shading: { fill: "D5E8F0", type: ShadingType.CLEAR }, 
                  margins: cellMargins,
                  children: [new Paragraph({ children: [new TextRun({ text: `${(income - expense).toLocaleString()} THB`, bold: true })] })] 
                }),
              ]
            }),
          ]
        }),
        new Paragraph({
            spacing: { before: 600 },
            children: [new TextRun({ text: "Generated by AI.EzDoc Universal Commander.", italic: true, size: 20 })]
        })
      ]
    }]
  });

  const fileName = `Financial_Report_Current.docx`;
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(`public/${fileName}`, buffer);
  
  console.log(JSON.stringify({
    url: `/${fileName}`,
    name: fileName,
    type: 'docx'
  }));
}

const args = process.argv.slice(2);
generateFinancialReport(args[0]).then(() => prisma.$disconnect());
